[build]
  command = "ng build -c production"
  publish = "dist/koi-sushi/browser"

[[plugins]]
  package = "@netlify/angular-runtime"

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"