[build]
  command = "ng build -c production"
  publish = "dist/koi-sushi/browser"

[[plugins]]
  package = "@netlify/angular-runtime"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Encoding = "br"
    Vary = "Accept-Encoding"